on:
  pull_request:
    branches:
      - main
name: PullRequest
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: NiklasLehnfeld/flutter-version-number-action@master
        with:
          file-path: example/pubspec.yaml

