on:
  pull_request:
    branches:
      - main
name: PullRequest
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: read-version
        uses: ./../flutter-version-number-action
        with:
          file-path: example/pubspec.yaml
      - run: echo ${{steps.read-version.outputs.version-number}}

